@domains = qw/1pointconnect.velantro.net
24hranyfood.velantro.net
69.12.68.28
aaatrucking.velantro.net
aabrothersexpress.velantro.net
aartrucking.velantro.net
absolute.velantro.net
accordtrucking.velantro.net
acrossamerica.velantro.net
adalogistics.velantro.net
adbrokerage.velantro.net
adcon.velantro.net
agafreight.velantro.net
aginianacc.velantro.net
agtlogistics.velantro.net
aimwestlogistics.velantro.net
akalfreightlogistics.velantro.net
akhaykexpress.velantro.net
allcityexpress.velantro.net
allday.velantro.net
allhaulingsolution.velantro.net
alliancelawgroup.velantro.net
allstatelogisticsllc.velantro.net
allstatetrucking.velantro.net
allwayexpress.velantro.net
americabestcare.velantro.net
americanbestcare.velantro.net
americanwayllc.velantro.net
americasfinestmed.velantro.net
anahitdanilyanlaw.velantro.net
angtransport.velantro.net
annascusine.velantro.net
arakelyan.velantro.net
arar.velantro.net
arauto.velantro.net
archive
arturtr.velantro.net
asafreight.velantro.net
autolineexpress.velantro.net
balbachtranspport.velantro.net
bellowsm.velantro.net
bestshaw.velantro.net
blackhawk.velantro.net
blueniletrucking.velantro.net
centuryoneinsurance.velantro.net
cfalogisticinc.velantro.net
chiulutax.velantro.net
clearinsuranceservice.velantro.net
comforth.velantro.net
conquestdispatchllc.velantro.net
crenshawdiemfg.velantro.net
dailylogistic.velantro.net
ddjtransport.velantro.net
dgds.velantro.net
dhaliwarbroscarriers.velantro.net
diabeticsolutions.velantro.net
dilanchianchiropractic.velantro.net
diratransportinc.velantro.net
dispatch.velantro.net
dispatchservicecorp.velantro.net
dronesx.velantro.net
droplogisticsllc.velantro.net
dtditech.velantro.net
dustindcolelogistics.velantro.net
eagle2enterprises.velantro.net
eaglecasttransportation.velantro.net
eddiesxpress.velantro.net
egllogistics.velantro.net
empiretrucking.velantro.net
enjlogistcs.velantro.net
estheticd.velantro.net
exittrans.velantro.net
exportzone.velantro.net
fidallc.velantro.net
firstcall.velantro.net
firstclass.velantro.net
firstcoasttruckinginc.velantro.net
firstmclogistic.velantro.net
fivestarexpress.velantro.net
foodexcatering.velantro.net
ftslogisticsllc.velantro.net
furiottellc.velantro.net
garystrucking.velantro.net
geder.velantro.net
gershman.velantro.net
globaloneforroyalsep.velantro.net
globustransportinc.velantro.net
gmctrucking.velantro.net
gmt.velantro.net
goldeneagletowing.velantro.net
goldstartransportllc.velantro.net
gotexpress.velantro.net
hausofpizza.velantro.net
haynes.velantro.net
hbmedtrans.velantro.net
hbmedtransp.velantro.net
hbrealestate.velantro.net
homecaregroup.velantro.net
identity.velantro.net
imexpressinc.velantro.net
imperialdispatch.velantro.net
infinitytransport.velantro.net
inreta.velantro.net
insurwideins.velantro.net
integritytrucking.velantro.net
interstatecargo.velantro.net
intextrans.velantro.net
intransit.velantro.net
itftrucking.velantro.net
jasmallc.velantro.net
jfrieght.velantro.net
jittransportinc.velantro.net
jlp.velantro.net
jlpdispatching.velantro.net
jnettrans.velantro.net
judicialguardllp.velantro.net
juicywingzinc.velantro.net
justelitetransport.velantro.net
kamedtransportation.velantro.net
karate.velantro.net
kempershuttle.velantro.net
kempershuttles.velantro.net
kingexpress.velantro.net
kingslanelogistic.velantro.net
kklogistic.velantro.net
kstartrans.velantro.net
ladental.velantro.net
landstarhq.velantro.net
lawestins.velantro.net
lawoffice.velantro.net
lecarforeigndomestic.velantro.net
lib.velantro.net
libs.velantro.net
limitlessgroup.velantro.net
lionheartexpedited.velantro.net
lmmj.velantro.net
maazinsuranceagency.velantro.net
mamavickys.velantro.net
minestone.velantro.net
miqoexpress.velantro.net
mjpanaexpress.velantro.net
mlogix2.managedlogix.net
mrtransmission.velantro.net
nalbandyan.velantro.net
nenicllc.velantro.net
nesexpress.velantro.net
netexpress.velantro.net
newwaymanagement.velantro.net
nmbholdingsllc.velantro.net
nnpropertymnagement.velantro.net
northcrestfinancial.velantro.net
nrgtrucking.velantro.net
onelogisticnetwork.velantro.net
oneupentertainment.velantro.net
onlinegenins.velantro.net
overnightllc.velantro.net
overnighttruckinginc.velantro.net
panexpress.velantro.net
papamurphy.velantro.net
pblk.velantro.net
pbxguide.velantro.net
perlas.velantro.net
piermont.velantro.net
pinhill.velantro.net
pompa.velantro.net
primecapital.velantro.net
primeexpressllc.velantro.net
primesourcetrucking.velantro.net
prioritytransportation.velantro.net
prontotracking.velantro.net
pul.velantro.net
pulnew.velantro.net
qualitydispatchingservices.velantro.net
queenstar.velantro.net
reliefhospice.velantro.net
reliefhospice2.velantro.net
relifund.velantro.net
roadkingllc.velantro.net
roadlinetrucking.velantro.net
royaltravel.velantro.net
rrtrans.velantro.net
rstransportation.velantro.net
rurtransportation.velantro.net
rvtrucking97.velantro.net
safetytransportllc.velantro.net
saya.velantro.net
shakhexpressllc.velantro.net
sharkslogistics.velantro.net
siexpressllc.velantro.net
silencelines.velantro.net
simplestepsfourlife.velantro.net
smilesdentistgr.velantro.net
smilesdentistgrp.velantro.net
solidarityhospicecare.velantro.net
solidwoodcloset.velantro.net
southtrans.velantro.net
srtruckingllc.velantro.net
starlinellc.velantro.net
statefarmanna.velantro.net
sterling.velantro.net
stitransportion.velantro.net
supportins.velantro.net
symbotictechnologics.velantro.net
synergylink.velantro.net
t-mobile.velantro.net
takelogistic.velantro.net
tcsl.velantro.net
texasfreightcoinc.velantro.net
threestripslogistics.velantro.net
tigran.velantro.net
titus.velantro.net
titusins.velantro.net
titusrealtypc.velantro.net
tjtransportation.velantro.net
touchofclass.velantro.net
transexpress.velantro.net
transselectlogistics.velantro.net
transwayexpress.velantro.net
ucdc.velantro.net
uniontrans.velantro.net
unitedcarecenterinc.velantro.net
unitedguardsecurity.velantro.net
unitedh.velantro.net
unitedmeds.velantro.net
unitedtransportation.velantro.net
unitedtransportllc.velantro.net
universaltrucking.velantro.net
usalogistics.velantro.net
usarmeniatravel.velantro.net
vcloudpbx.velantro.net
verifpros.velantro.net
vip.velantro.net
visaconcordtravel.velantro.net
vivendi.velantro.net
vvlogistic.velantro.net
westautosl.velantro.net
wingstopcrenshaw.velantro.net
wingstophq.velantro.net
yanasllc.velantro.net
yitotrucking.velantro.net
zakstransportation.velantro.net
/;

for $d (@domains) {
	$cmd = "rm -rfv /mnt/s3/usr/local/freeswitch/recordings/$d/archive/2017\n";
	system($cmd);
	$cmd = "rm -rfv /mnt/s3/usr/local/freeswitch/recordings/$d/archive/2018\n";
	system($cmd);
	$cmd = "rm -rfv /mnt/s3/usr/local/freeswitch/recordings/$d/archive/2019\n";
	system($cmd);
	
}
